spring:
   redis:
      database: 0
      host: 127.0.0.1
      # 如果使用的jedis 则将lettuce改成jedis即可
      lettuce:
        pool:
          # 最大活跃链接数 默认8
          max-active: 8
          # 最大空闲连接数 默认8
          max-idle: 8
          # 最小空闲连接数 默认0
          min-idle: 0
      password: '123456'
      port: 6379
      ssl: false
      timeout: 5000
wx:
  mp:
    configs:
       - appId: wx2b51a90ef63a2af0
         secret: 4c5d38119be9377a62583dc4f53df570
         token: cdf7ed76bfc44b12a44a4fae64633deb
         aesKey:
logging:
    config: classpath:logback-spring.xml

