spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/kochun-weixin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        password: root
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        # hikari 连接池  https://blog.csdn.net/X5fnncxzq4/article/details/80649679
        hikari:
            # 自动提交
            auto-commit: true
            connection-test-query: SELECT 1
            # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
            # 生产环境 connect-time 10 s
            connection-timeout: 9000
            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
            idle-timeout: 600000
            # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout 7200s 参数（# 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->  ） -->
            max-lifetime: 1800000
            # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
            maximum-pool-size: 15
            # 最小连接数
            minimum-idle: 10
            # 连接池名字
            pool-name: DemoHikariCP
    redis:
      database: 0
      host: 127.0.0.1
      # 如果使用的jedis 则将lettuce改成jedis即可
      lettuce:
        pool:
          # 最大活跃链接数 默认8
          max-active: 8
          # 最大空闲连接数 默认8
          max-idle: 8
          # 最小空闲连接数 默认0
          min-idle: 0
      password: '123456'
      port: 6379
      ssl: false
      timeout: 5000
wx:
  mp:
    configs:
       - appId: wx2b51a90ef63a2af0
         secret: 4c5d38119be9377a62583dc4f53df570
         token: cdf7ed76bfc44b12a44a4fae64633deb
         aesKey:
logging:
    config: classpath:logback-spring.xml
#dubbo配置
dubbo:
  scan:
    base-packages: com.kochun.wxmp.service
    # Dubbo Protocol
  protocol:
     name : dubbo
  ## Random port
     port : -1
  ## Dubbo Registry
  registry:
     address: zookeeper://127.0.0.1:2181
     #file: ${user.name}/dubbo-cache/${spring.application.name}/dubbo.cache

